### ISSUE TITLE
Default state values

### ISSUE THREAD

**Issue by bobbysebolao** [FAC-Sixteen/b-b#9]
Nice job with handling the states and effects for the quiz questions! In index.js in the questionContainer folder, I was a bit confused by the default correct state of "correct" on line 8. You later set the state to be a boolean after the player has answered the question, so I was wondering why it's set to be 'correct' (as opposed to just an empty string, or null) in the first place.

**Comment by Baalwaan** [comment]
Thank for your advise Bobby. I worked with NULL
